### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by lietochris** [Larry850806/facebook-chat-bot#1]
**as I fix this? please  :,(**

Important: use process.env.PORT as the port and process.env.IP as the host in your scripts!

Debugger listening on port 15454
info init db 
info init db OK
info init respond 
info init respond OK
info init question 
info init question OK
info init sys 
info init sys OK
info Logging in... 
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 52.27.9.64:80
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at TCPConnectWrap.afterConnect [as oncomplete](net.js:1061:14)

**Comment by LarryLuTW** [comment]
Thanks for your report. I think I know where the problem is. I will take a look and fix it as soon as possible.

**Comment by LarryLuTW** [comment]
I have published new version [v2.0.0-alpha](https://github.com/Larry850806/facebook-chat-bot/releases/tag/v2.0.0-alpha).
This issue is solved In this version.
